import { Helmet } from "react-helmet-async";


const SEO =()=>{

return(

<Helmet>

    <title>
            Pradeep | Frontend Developer
    </title>


    <meta
        name="description"
        content="
        Frontend Developer specializing in React, Next.js, TypeScript, Finance Dashboard and Automation.
        "
    />


    <meta
        name="keywords"
        content="
        React Developer, Next.js Developer, Frontend Developer, Loan CRM, Google Apps Script
"
    />


</Helmet>

)

}


export default SEO;